/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pNbGo1JnjtEErG6Lk1GLW5
// Component: uEhW5GYsP8Js

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: KS0d0aYJ-PHT/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: pNbGo1JnjtEErG6Lk1GLW5/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: pNbGo1JnjtEErG6Lk1GLW5/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: pNbGo1JnjtEErG6Lk1GLW5/projectcss
import sty from "./PlasmicPriceCard.module.css"; // plasmic-import: uEhW5GYsP8Js/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: cmh4K1iW3GRi/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: Do5boxSPSliQ/icon

createPlasmicElementProxy;

export type PlasmicPriceCard__VariantMembers = {
  primary: "primary";
  borders: "flatLeft" | "flatRight" | "flatCenter";
};
export type PlasmicPriceCard__VariantsArgs = {
  primary?: SingleBooleanChoiceArg<"primary">;
  borders?: MultiChoiceArg<"flatLeft" | "flatRight" | "flatCenter">;
};
type VariantPropType = keyof PlasmicPriceCard__VariantsArgs;
export const PlasmicPriceCard__VariantProps = new Array<VariantPropType>(
  "primary",
  "borders"
);

export type PlasmicPriceCard__ArgsType = {};
type ArgPropType = keyof PlasmicPriceCard__ArgsType;
export const PlasmicPriceCard__ArgProps = new Array<ArgPropType>();

export type PlasmicPriceCard__OverridesType = {
  root?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  h4?: Flex__<"h4">;
  link?: Flex__<"a">;
  button?: Flex__<typeof Button>;
};

export interface DefaultPriceCardProps {
  primary?: SingleBooleanChoiceArg<"primary">;
  borders?: MultiChoiceArg<"flatLeft" | "flatRight" | "flatCenter">;
  className?: string;
}

const $$ = {};

function PlasmicPriceCard__RenderFunc(props: {
  variants: PlasmicPriceCard__VariantsArgs;
  args: PlasmicPriceCard__ArgsType;
  overrides: PlasmicPriceCard__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "primary",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.primary
      },
      {
        path: "borders",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.borders
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = _useGlobalVariants();
  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        {
          [sty.rootborders_flatCenter]: hasVariant(
            $state,
            "borders",
            "flatCenter"
          ),
          [sty.rootborders_flatLeft]: hasVariant($state, "borders", "flatLeft"),
          [sty.rootborders_flatRight]: hasVariant(
            $state,
            "borders",
            "flatRight"
          ),
          [sty.rootprimary]: hasVariant($state, "primary", "primary")
        }
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox, {
          [sty.freeBoxborders_flatCenter]: hasVariant(
            $state,
            "borders",
            "flatCenter"
          ),
          [sty.freeBoxborders_flatLeft]: hasVariant(
            $state,
            "borders",
            "flatLeft"
          ),
          [sty.freeBoxborders_flatRight]: hasVariant(
            $state,
            "borders",
            "flatRight"
          ),
          [sty.freeBoxprimary]: hasVariant($state, "primary", "primary")
        })}
      >
        <h4
          data-plasmic-name={"h4"}
          data-plasmic-override={overrides.h4}
          className={classNames(
            projectcss.all,
            projectcss.h4,
            projectcss.__wab_text,
            sty.h4,
            {
              [sty.h4borders_flatCenter]: hasVariant(
                $state,
                "borders",
                "flatCenter"
              ),
              [sty.h4borders_flatLeft]: hasVariant(
                $state,
                "borders",
                "flatLeft"
              ),
              [sty.h4borders_flatRight]: hasVariant(
                $state,
                "borders",
                "flatRight"
              )
            }
          )}
        >
          {hasVariant($state, "borders", "flatRight")
            ? "Enterprise"
            : hasVariant($state, "borders", "flatLeft")
            ? "Free"
            : "Pro"}
        </h4>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__mqbm4,
            {
              [sty.textborders_flatCenter__mqbm4XIeyp]: hasVariant(
                $state,
                "borders",
                "flatCenter"
              ),
              [sty.textborders_flatLeft__mqbm4K3Sr5]: hasVariant(
                $state,
                "borders",
                "flatLeft"
              ),
              [sty.textborders_flatRight__mqbm4X97Nv]: hasVariant(
                $state,
                "borders",
                "flatRight"
              ),
              [sty.textprimary__mqbm4CqdP]: hasVariant(
                $state,
                "primary",
                "primary"
              )
            }
          )}
        >
          {hasVariant($state, "borders", "flatRight")
            ? "Flexible power and security"
            : hasVariant($state, "borders", "flatLeft")
            ? "A complete analytics platform."
            : "A complete analytics platform."}
        </div>
        <PlasmicImg__
          alt={""}
          className={classNames(sty.img__ojfUb)}
          displayHeight={"auto"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"auto"}
          loading={"lazy"}
          src={{
            src: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAACCAYAAAGVq9ERAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAMklEQVRIiWPQ0tLiGYyYYaAdMGQcpTVI8WhgDYJI0BqGeDRhDYJIGMWjYTCaBrSIKrAAugVDgL2OLdoAAAAASUVORK5CYII=",
            fullWidth: 300,
            fullHeight: 2
          }}
        />

        <div
          className={classNames(projectcss.all, sty.columns__xzIbd, {
            [sty.columnsprimary__xzIbdCqdP]: hasVariant(
              $state,
              "primary",
              "primary"
            )
          })}
        >
          <div className={classNames(projectcss.all, sty.column__utwI2)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__wzyTh, {
                [sty.imgborders_flatLeft__wzyTHk3Sr5]: hasVariant(
                  $state,
                  "borders",
                  "flatLeft"
                )
              })}
              displayHeight={"24px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"24px"}
              loading={"lazy"}
              src={
                hasVariant($state, "borders", "flatLeft")
                  ? {
                      src: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACYAAAAnCAYAAAEUZgqdAAAACXBIWXMAABYlAAAWJQFJUiTwAAAA00lEQVRYhe2X4RGDIAxGGYERHKkbdJSO4kgdoaO8nld6RkSLEZG2ef9A78tHCFGcUwEgB/fJREGATg76ycRxzNYzxB3iyxdWvfDKSg2zdeDTFqdyRpbC+8H2EEYelKhERjp1pCyRuLXIk7dZZEVULxID+NmkYVQEuJQSuqWO3R6hxxcKESjiCPApQfXSiAR35wghWCrZvoiQYRjGb4Jo3E1cGRkN0YQx/sIQcNX+dnFUhsI3PL4x9c1sGZkGOauGlgzSSlEvGGyqH/lgsA1DhuF0PAGxc0ZL+SLdRQAAAABJRU5ErkJggg==",
                      fullWidth: 38,
                      fullHeight: 39
                    }
                  : {
                      src: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAAEgBckRAAAACXBIWXMAABYlAAAWJQFJUiTwAAABLklEQVRoge2Y0Q2CMBCGu4TJzxsjOI5pX9zEEXQD3MqkJWEER8BAJBYo2EoLR7zvhQDl/v+OKxSEWAxkWVk7ph4dHJ5cA7i04H1wPeCq1NRAzHm1a79xUjskk+bpPRgh5Z0cDKlHN+prZFgXedtwKTHMm+6JEb1F8Etgn8FY4ribDa6LEbMUthBS1dgWih6YYRhi4FzlzWw/SH1MFhzS1JnUt2TBofT9D4JD6QLSXJIEb/i8YNwiWFoWnB75lAhi1dwlgtg31BbJlLkm6ZZBJnX0VuyJqATBGYZhGGYj0L76y6LZih0ar3orAN9fvPSMG/orDDbuC05xJtPqFc/stfrMpw7ZVkG7XLd/BoYlQqbHEZgIGeOhiZA1HpAIbePeiVA3PpnI3owzDMOIGLwAhvTUiS/PwiUAAAAASUVORK5CYII=",
                      fullWidth: 48,
                      fullHeight: 48
                    }
              }
            />
          </div>
          <div
            className={classNames(projectcss.all, sty.column__x8LRd, {
              [sty.columnborders_flatRight__x8LRdX97Nv]: hasVariant(
                $state,
                "borders",
                "flatRight"
              )
            })}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__xezDa,
                {
                  [sty.textborders_flatLeft__xezDAk3Sr5]: hasVariant(
                    $state,
                    "borders",
                    "flatLeft"
                  ),
                  [sty.textborders_flatRight__xezDax97Nv]: hasVariant(
                    $state,
                    "borders",
                    "flatRight"
                  ),
                  [sty.textprimary__xezDaCqdP]: hasVariant(
                    $state,
                    "primary",
                    "primary"
                  )
                }
              )}
            >
              {hasVariant($state, "borders", "flatRight")
                ? "Everything in pro"
                : hasVariant($state, "borders", "flatLeft")
                ? "1 Product"
                : "Up to 10 projects"}
            </div>
          </div>
        </div>
        <div
          className={classNames(projectcss.all, sty.columns__lqBw, {
            [sty.columnsborders_flatCenter__lqBwXIeyp]: hasVariant(
              $state,
              "borders",
              "flatCenter"
            ),
            [sty.columnsborders_flatLeft__lqBwk3Sr5]: hasVariant(
              $state,
              "borders",
              "flatLeft"
            ),
            [sty.columnsborders_flatRight__lqBwX97Nv]: hasVariant(
              $state,
              "borders",
              "flatRight"
            ),
            [sty.columnsprimary__lqBwCqdP]: hasVariant(
              $state,
              "primary",
              "primary"
            )
          })}
        >
          <div className={classNames(projectcss.all, sty.column__yz9N9)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__uBBsh, {
                [sty.imgborders_flatLeft__uBBshk3Sr5]: hasVariant(
                  $state,
                  "borders",
                  "flatLeft"
                )
              })}
              displayHeight={"24px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"24px"}
              loading={"lazy"}
              src={
                hasVariant($state, "borders", "flatLeft")
                  ? {
                      src: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACYAAAAnCAYAAAEUZgqdAAAACXBIWXMAABYlAAAWJQFJUiTwAAAA00lEQVRYhe2X4RGDIAxGGYERHKkbdJSO4kgdoaO8nld6RkSLEZG2ef9A78tHCFGcUwEgB/fJREGATg76ycRxzNYzxB3iyxdWvfDKSg2zdeDTFqdyRpbC+8H2EEYelKhERjp1pCyRuLXIk7dZZEVULxID+NmkYVQEuJQSuqWO3R6hxxcKESjiCPApQfXSiAR35wghWCrZvoiQYRjGb4Jo3E1cGRkN0YQx/sIQcNX+dnFUhsI3PL4x9c1sGZkGOauGlgzSSlEvGGyqH/lgsA1DhuF0PAGxc0ZL+SLdRQAAAABJRU5ErkJggg==",
                      fullWidth: 38,
                      fullHeight: 39
                    }
                  : {
                      src: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAAEgBckRAAAACXBIWXMAABYlAAAWJQFJUiTwAAABLklEQVRoge2Y0Q2CMBCGu4TJzxsjOI5pX9zEEXQD3MqkJWEER8BAJBYo2EoLR7zvhQDl/v+OKxSEWAxkWVk7ph4dHJ5cA7i04H1wPeCq1NRAzHm1a79xUjskk+bpPRgh5Z0cDKlHN+prZFgXedtwKTHMm+6JEb1F8Etgn8FY4ribDa6LEbMUthBS1dgWih6YYRhi4FzlzWw/SH1MFhzS1JnUt2TBofT9D4JD6QLSXJIEb/i8YNwiWFoWnB75lAhi1dwlgtg31BbJlLkm6ZZBJnX0VuyJqATBGYZhGGYj0L76y6LZih0ar3orAN9fvPSMG/orDDbuC05xJtPqFc/stfrMpw7ZVkG7XLd/BoYlQqbHEZgIGeOhiZA1HpAIbePeiVA3PpnI3owzDMOIGLwAhvTUiS/PwiUAAAAASUVORK5CYII=",
                      fullWidth: 48,
                      fullHeight: 48
                    }
              }
            />
          </div>
          <div className={classNames(projectcss.all, sty.column__vPJ)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__zw1Bw,
                {
                  [sty.textborders_flatCenter__zw1BwXIeyp]: hasVariant(
                    $state,
                    "borders",
                    "flatCenter"
                  ),
                  [sty.textborders_flatLeft__zw1Bwk3Sr5]: hasVariant(
                    $state,
                    "borders",
                    "flatLeft"
                  ),
                  [sty.textborders_flatRight__zw1BwX97Nv]: hasVariant(
                    $state,
                    "borders",
                    "flatRight"
                  ),
                  [sty.textprimary__zw1BwCqdP]: hasVariant(
                    $state,
                    "primary",
                    "primary"
                  )
                }
              )}
            >
              {hasVariant($state, "borders", "flatRight")
                ? "Volume discount"
                : hasVariant($state, "borders", "flatLeft")
                ? "Analytics board"
                : hasVariant($state, "primary", "primary")
                ? "Analytics board"
                : "Up to 10 projects"}
            </div>
          </div>
        </div>
        <div
          className={classNames(projectcss.all, sty.columns__zsBer, {
            [sty.columnsborders_flatCenter__zsBerxIeyp]: hasVariant(
              $state,
              "borders",
              "flatCenter"
            ),
            [sty.columnsborders_flatLeft__zsBeRk3Sr5]: hasVariant(
              $state,
              "borders",
              "flatLeft"
            ),
            [sty.columnsprimary__zsBerCqdP]: hasVariant(
              $state,
              "primary",
              "primary"
            )
          })}
        >
          <div className={classNames(projectcss.all, sty.column__atSvf)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__oboSk, {
                [sty.imgborders_flatLeft__oboSKk3Sr5]: hasVariant(
                  $state,
                  "borders",
                  "flatLeft"
                )
              })}
              displayHeight={"24px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"24px"}
              loading={"lazy"}
              src={
                hasVariant($state, "borders", "flatLeft")
                  ? {
                      src: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACYAAAAnCAYAAAEUZgqdAAAACXBIWXMAABYlAAAWJQFJUiTwAAAA00lEQVRYhe2X4RGDIAxGGYERHKkbdJSO4kgdoaO8nld6RkSLEZG2ef9A78tHCFGcUwEgB/fJREGATg76ycRxzNYzxB3iyxdWvfDKSg2zdeDTFqdyRpbC+8H2EEYelKhERjp1pCyRuLXIk7dZZEVULxID+NmkYVQEuJQSuqWO3R6hxxcKESjiCPApQfXSiAR35wghWCrZvoiQYRjGb4Jo3E1cGRkN0YQx/sIQcNX+dnFUhsI3PL4x9c1sGZkGOauGlgzSSlEvGGyqH/lgsA1DhuF0PAGxc0ZL+SLdRQAAAABJRU5ErkJggg==",
                      fullWidth: 38,
                      fullHeight: 39
                    }
                  : {
                      src: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAAEgBckRAAAACXBIWXMAABYlAAAWJQFJUiTwAAABLklEQVRoge2Y0Q2CMBCGu4TJzxsjOI5pX9zEEXQD3MqkJWEER8BAJBYo2EoLR7zvhQDl/v+OKxSEWAxkWVk7ph4dHJ5cA7i04H1wPeCq1NRAzHm1a79xUjskk+bpPRgh5Z0cDKlHN+prZFgXedtwKTHMm+6JEb1F8Etgn8FY4ribDa6LEbMUthBS1dgWih6YYRhi4FzlzWw/SH1MFhzS1JnUt2TBofT9D4JD6QLSXJIEb/i8YNwiWFoWnB75lAhi1dwlgtg31BbJlLkm6ZZBJnX0VuyJqATBGYZhGGYj0L76y6LZih0ar3orAN9fvPSMG/orDDbuC05xJtPqFc/stfrMpw7ZVkG7XLd/BoYlQqbHEZgIGeOhiZA1HpAIbePeiVA3PpnI3owzDMOIGLwAhvTUiS/PwiUAAAAASUVORK5CYII=",
                      fullWidth: 48,
                      fullHeight: 48
                    }
              }
            />
          </div>
          <div
            className={classNames(projectcss.all, sty.column___7QLi0, {
              [sty.columnborders_flatLeft___7QLi0K3Sr5]: hasVariant(
                $state,
                "borders",
                "flatLeft"
              ),
              [sty.columnborders_flatRight___7QLi0X97Nv]: hasVariant(
                $state,
                "borders",
                "flatRight"
              ),
              [sty.columnprimary___7QLi0CqdP]: hasVariant(
                $state,
                "primary",
                "primary"
              )
            })}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___4Frvr,
                {
                  [sty.textborders_flatLeft___4FrvRk3Sr5]: hasVariant(
                    $state,
                    "borders",
                    "flatLeft"
                  ),
                  [sty.textprimary___4FrvrCqdP]: hasVariant(
                    $state,
                    "primary",
                    "primary"
                  )
                }
              )}
            >
              {hasVariant($state, "borders", "flatLeft")
                ? "Insights panel"
                : hasVariant($state, "primary", "primary")
                ? "Analytics board"
                : "Up to 10 projects"}
            </div>
          </div>
          <div
            className={classNames(projectcss.all, sty.column__h6C8L, {
              [sty.columnborders_flatLeft__h6C8Lk3Sr5]: hasVariant(
                $state,
                "borders",
                "flatLeft"
              ),
              [sty.columnborders_flatRight__h6C8LX97Nv]: hasVariant(
                $state,
                "borders",
                "flatRight"
              ),
              [sty.columnprimary__h6C8LCqdP]: hasVariant(
                $state,
                "primary",
                "primary"
              )
            })}
          />
        </div>
        {(
          hasVariant($state, "borders", "flatCenter")
            ? true
            : hasVariant($state, "borders", "flatLeft")
            ? true
            : hasVariant($state, "primary", "primary")
            ? true
            : hasVariant(globalVariants, "screen", "mobileOnly")
            ? true
            : false
        ) ? (
          <div
            className={classNames(projectcss.all, sty.columns__sipIe, {
              [sty.columnsborders_flatCenter__sipIexIeyp]: hasVariant(
                $state,
                "borders",
                "flatCenter"
              ),
              [sty.columnsborders_flatLeft__sipIEk3Sr5]: hasVariant(
                $state,
                "borders",
                "flatLeft"
              ),
              [sty.columnsprimary__sipIeCqdP]: hasVariant(
                $state,
                "primary",
                "primary"
              )
            })}
          >
            <div className={classNames(projectcss.all, sty.column__z17Tj)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___0ZJul, {
                  [sty.imgborders_flatLeft___0ZJuLk3Sr5]: hasVariant(
                    $state,
                    "borders",
                    "flatLeft"
                  )
                })}
                displayHeight={"24px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"24px"}
                loading={"lazy"}
                src={
                  hasVariant($state, "borders", "flatLeft")
                    ? {
                        src: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACYAAAAnCAYAAAEUZgqdAAAACXBIWXMAABYlAAAWJQFJUiTwAAAA00lEQVRYhe2X4RGDIAxGGYERHKkbdJSO4kgdoaO8nld6RkSLEZG2ef9A78tHCFGcUwEgB/fJREGATg76ycRxzNYzxB3iyxdWvfDKSg2zdeDTFqdyRpbC+8H2EEYelKhERjp1pCyRuLXIk7dZZEVULxID+NmkYVQEuJQSuqWO3R6hxxcKESjiCPApQfXSiAR35wghWCrZvoiQYRjGb4Jo3E1cGRkN0YQx/sIQcNX+dnFUhsI3PL4x9c1sGZkGOauGlgzSSlEvGGyqH/lgsA1DhuF0PAGxc0ZL+SLdRQAAAABJRU5ErkJggg==",
                        fullWidth: 38,
                        fullHeight: 39
                      }
                    : {
                        src: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAAEgBckRAAAACXBIWXMAABYlAAAWJQFJUiTwAAABLklEQVRoge2Y0Q2CMBCGu4TJzxsjOI5pX9zEEXQD3MqkJWEER8BAJBYo2EoLR7zvhQDl/v+OKxSEWAxkWVk7ph4dHJ5cA7i04H1wPeCq1NRAzHm1a79xUjskk+bpPRgh5Z0cDKlHN+prZFgXedtwKTHMm+6JEb1F8Etgn8FY4ribDa6LEbMUthBS1dgWih6YYRhi4FzlzWw/SH1MFhzS1JnUt2TBofT9D4JD6QLSXJIEb/i8YNwiWFoWnB75lAhi1dwlgtg31BbJlLkm6ZZBJnX0VuyJqATBGYZhGGYj0L76y6LZih0ar3orAN9fvPSMG/orDDbuC05xJtPqFc/stfrMpw7ZVkG7XLd/BoYlQqbHEZgIGeOhiZA1HpAIbePeiVA3PpnI3owzDMOIGLwAhvTUiS/PwiUAAAAASUVORK5CYII=",
                        fullWidth: 48,
                        fullHeight: 48
                      }
                }
              />
            </div>
            <div className={classNames(projectcss.all, sty.column__eGgs6)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jXgez,
                  {
                    [sty.textborders_flatLeft__jXgezk3Sr5]: hasVariant(
                      $state,
                      "borders",
                      "flatLeft"
                    ),
                    [sty.textprimary__jXgezCqdP]: hasVariant(
                      $state,
                      "primary",
                      "primary"
                    )
                  }
                )}
              >
                {hasVariant($state, "borders", "flatLeft")
                  ? "CLI access"
                  : hasVariant($state, "primary", "primary")
                  ? "Analytics board"
                  : "Up to 10 projects"}
              </div>
            </div>
          </div>
        ) : null}
        {(
          hasVariant($state, "borders", "flatCenter")
            ? true
            : hasVariant($state, "primary", "primary")
            ? true
            : false
        ) ? (
          <div
            className={classNames(projectcss.all, sty.columns__klDTo, {
              [sty.columnsborders_flatCenter__klDToXIeyp]: hasVariant(
                $state,
                "borders",
                "flatCenter"
              ),
              [sty.columnsprimary__klDToCqdP]: hasVariant(
                $state,
                "primary",
                "primary"
              )
            })}
          >
            <div className={classNames(projectcss.all, sty.column__lgP2)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___8WOz1)}
                displayHeight={"24px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"24px"}
                loading={"lazy"}
                src={{
                  src: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAAEgBckRAAAACXBIWXMAABYlAAAWJQFJUiTwAAABLklEQVRoge2Y0Q2CMBCGu4TJzxsjOI5pX9zEEXQD3MqkJWEER8BAJBYo2EoLR7zvhQDl/v+OKxSEWAxkWVk7ph4dHJ5cA7i04H1wPeCq1NRAzHm1a79xUjskk+bpPRgh5Z0cDKlHN+prZFgXedtwKTHMm+6JEb1F8Etgn8FY4ribDa6LEbMUthBS1dgWih6YYRhi4FzlzWw/SH1MFhzS1JnUt2TBofT9D4JD6QLSXJIEb/i8YNwiWFoWnB75lAhi1dwlgtg31BbJlLkm6ZZBJnX0VuyJqATBGYZhGGYj0L76y6LZih0ar3orAN9fvPSMG/orDDbuC05xJtPqFc/stfrMpw7ZVkG7XLd/BoYlQqbHEZgIGeOhiZA1HpAIbePeiVA3PpnI3owzDMOIGLwAhvTUiS/PwiUAAAAASUVORK5CYII=",
                  fullWidth: 48,
                  fullHeight: 48
                }}
              />
            </div>
            <div className={classNames(projectcss.all, sty.column__oFht)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bHrZ,
                  {
                    [sty.textborders_flatCenter__bHrZXIeyp]: hasVariant(
                      $state,
                      "borders",
                      "flatCenter"
                    ),
                    [sty.textprimary__bHrZCqdP]: hasVariant(
                      $state,
                      "primary",
                      "primary"
                    )
                  }
                )}
              >
                {"Insights panel"}
              </div>
            </div>
          </div>
        ) : null}
        {(
          hasVariant($state, "borders", "flatCenter")
            ? true
            : hasVariant($state, "primary", "primary")
            ? true
            : false
        ) ? (
          <div
            className={classNames(projectcss.all, sty.columns__hHqrv, {
              [sty.columnsborders_flatCenter__hHqrvXIeyp]: hasVariant(
                $state,
                "borders",
                "flatCenter"
              ),
              [sty.columnsprimary__hHqrvCqdP]: hasVariant(
                $state,
                "primary",
                "primary"
              )
            })}
          >
            <div className={classNames(projectcss.all, sty.column__he1Yd)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__xMs1J)}
                displayHeight={"24px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "16px"
                    : "24px"
                }
                loading={"lazy"}
                src={{
                  src: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAAEgBckRAAAACXBIWXMAABYlAAAWJQFJUiTwAAABLklEQVRoge2Y0Q2CMBCGu4TJzxsjOI5pX9zEEXQD3MqkJWEER8BAJBYo2EoLR7zvhQDl/v+OKxSEWAxkWVk7ph4dHJ5cA7i04H1wPeCq1NRAzHm1a79xUjskk+bpPRgh5Z0cDKlHN+prZFgXedtwKTHMm+6JEb1F8Etgn8FY4ribDa6LEbMUthBS1dgWih6YYRhi4FzlzWw/SH1MFhzS1JnUt2TBofT9D4JD6QLSXJIEb/i8YNwiWFoWnB75lAhi1dwlgtg31BbJlLkm6ZZBJnX0VuyJqATBGYZhGGYj0L76y6LZih0ar3orAN9fvPSMG/orDDbuC05xJtPqFc/stfrMpw7ZVkG7XLd/BoYlQqbHEZgIGeOhiZA1HpAIbePeiVA3PpnI3owzDMOIGLwAhvTUiS/PwiUAAAAASUVORK5CYII=",
                  fullWidth: 48,
                  fullHeight: 48
                }}
              />
            </div>
            <div className={classNames(projectcss.all, sty.column__eOo5D)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qgLdN,
                  {
                    [sty.textprimary__qgLdNCqdP]: hasVariant(
                      $state,
                      "primary",
                      "primary"
                    )
                  }
                )}
              >
                {"CLI access"}
              </div>
            </div>
          </div>
        ) : null}
        {(
          hasVariant($state, "borders", "flatCenter")
            ? true
            : hasVariant($state, "primary", "primary")
            ? true
            : false
        ) ? (
          <div
            className={classNames(projectcss.all, sty.columns__pp40Z, {
              [sty.columnsborders_flatCenter__pp40ZXIeyp]: hasVariant(
                $state,
                "borders",
                "flatCenter"
              ),
              [sty.columnsprimary__pp40ZCqdP]: hasVariant(
                $state,
                "primary",
                "primary"
              )
            })}
          >
            <div className={classNames(projectcss.all, sty.column__hx7Vy)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___9Dcy6)}
                displayHeight={"24px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"24px"}
                loading={"lazy"}
                src={{
                  src: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAAEgBckRAAAACXBIWXMAABYlAAAWJQFJUiTwAAABLklEQVRoge2Y0Q2CMBCGu4TJzxsjOI5pX9zEEXQD3MqkJWEER8BAJBYo2EoLR7zvhQDl/v+OKxSEWAxkWVk7ph4dHJ5cA7i04H1wPeCq1NRAzHm1a79xUjskk+bpPRgh5Z0cDKlHN+prZFgXedtwKTHMm+6JEb1F8Etgn8FY4ribDa6LEbMUthBS1dgWih6YYRhi4FzlzWw/SH1MFhzS1JnUt2TBofT9D4JD6QLSXJIEb/i8YNwiWFoWnB75lAhi1dwlgtg31BbJlLkm6ZZBJnX0VuyJqATBGYZhGGYj0L76y6LZih0ar3orAN9fvPSMG/orDDbuC05xJtPqFc/stfrMpw7ZVkG7XLd/BoYlQqbHEZgIGeOhiZA1HpAIbePeiVA3PpnI3owzDMOIGLwAhvTUiS/PwiUAAAAASUVORK5CYII=",
                  fullWidth: 48,
                  fullHeight: 48
                }}
              />
            </div>
            <div className={classNames(projectcss.all, sty.column__q1KnF)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__syAwq,
                  {
                    [sty.textprimary__syAwqCqdP]: hasVariant(
                      $state,
                      "primary",
                      "primary"
                    )
                  }
                )}
              >
                {"Automation features"}
              </div>
            </div>
          </div>
        ) : null}
        {(
          hasVariant($state, "borders", "flatCenter")
            ? true
            : hasVariant($state, "primary", "primary")
            ? true
            : false
        ) ? (
          <div
            className={classNames(projectcss.all, sty.columns__budLh, {
              [sty.columnsborders_flatCenter__budLhXIeyp]: hasVariant(
                $state,
                "borders",
                "flatCenter"
              ),
              [sty.columnsprimary__budLhCqdP]: hasVariant(
                $state,
                "primary",
                "primary"
              )
            })}
          >
            <div className={classNames(projectcss.all, sty.column___8Gokh)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__nDZlc)}
                displayHeight={"24px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"24px"}
                loading={"lazy"}
                src={{
                  src: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAAEgBckRAAAACXBIWXMAABYlAAAWJQFJUiTwAAABLklEQVRoge2Y0Q2CMBCGu4TJzxsjOI5pX9zEEXQD3MqkJWEER8BAJBYo2EoLR7zvhQDl/v+OKxSEWAxkWVk7ph4dHJ5cA7i04H1wPeCq1NRAzHm1a79xUjskk+bpPRgh5Z0cDKlHN+prZFgXedtwKTHMm+6JEb1F8Etgn8FY4ribDa6LEbMUthBS1dgWih6YYRhi4FzlzWw/SH1MFhzS1JnUt2TBofT9D4JD6QLSXJIEb/i8YNwiWFoWnB75lAhi1dwlgtg31BbJlLkm6ZZBJnX0VuyJqATBGYZhGGYj0L76y6LZih0ar3orAN9fvPSMG/orDDbuC05xJtPqFc/stfrMpw7ZVkG7XLd/BoYlQqbHEZgIGeOhiZA1HpAIbePeiVA3PpnI3owzDMOIGLwAhvTUiS/PwiUAAAAASUVORK5CYII=",
                  fullWidth: 48,
                  fullHeight: 48
                }}
              />
            </div>
            <div className={classNames(projectcss.all, sty.column__yHtFl)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fFnuu,
                  {
                    [sty.textprimary__fFnuuCqdP]: hasVariant(
                      $state,
                      "primary",
                      "primary"
                    )
                  }
                )}
              >
                {"Team features"}
              </div>
            </div>
          </div>
        ) : null}
        <PlasmicImg__
          alt={""}
          className={classNames(sty.img__ptq5V)}
          displayHeight={"auto"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"auto"}
          loading={"lazy"}
          src={{
            src: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAACCAYAAAGVq9ERAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAMklEQVRIiWPQ0tLiGYyYYaAdMGQcpTVI8WhgDYJI0BqGeDRhDYJIGMWjYTCaBrSIKrAAugVDgL2OLdoAAAAASUVORK5CYII=",
            fullWidth: 300,
            fullHeight: 2
          }}
        />

        {(
          hasVariant($state, "borders", "flatCenter")
            ? true
            : hasVariant($state, "borders", "flatRight")
            ? true
            : hasVariant($state, "borders", "flatLeft")
            ? true
            : false
        ) ? (
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__mUFrj,
              {
                [sty.textborders_flatCenter__mUFrjXIeyp]: hasVariant(
                  $state,
                  "borders",
                  "flatCenter"
                ),
                [sty.textborders_flatLeft__mUFrjk3Sr5]: hasVariant(
                  $state,
                  "borders",
                  "flatLeft"
                ),
                [sty.textborders_flatRight__mUFrjX97Nv]: hasVariant(
                  $state,
                  "borders",
                  "flatRight"
                )
              }
            )}
          >
            {hasVariant($state, "borders", "flatCenter")
              ? "$ 50"
              : hasVariant($state, "borders", "flatRight")
              ? "$ 800"
              : "$ 0"}
          </div>
        ) : null}
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___86Skh,
            {
              [sty.textborders_flatCenter___86SkhxIeyp]: hasVariant(
                $state,
                "borders",
                "flatCenter"
              ),
              [sty.textborders_flatLeft___86SkHk3Sr5]: hasVariant(
                $state,
                "borders",
                "flatLeft"
              ),
              [sty.textborders_flatRight___86Skhx97Nv]: hasVariant(
                $state,
                "borders",
                "flatRight"
              )
            }
          )}
        >
          {hasVariant($state, "borders", "flatRight")
            ? "Starting price, customizable"
            : hasVariant($state, "borders", "flatLeft")
            ? "Free Forever"
            : "per project/month"}
        </div>
        <PlasmicLink__
          data-plasmic-name={"link"}
          data-plasmic-override={overrides.link}
          className={classNames(projectcss.all, projectcss.a, sty.link)}
          href={"#"}
          platform={"react"}
        >
          <Button
            data-plasmic-name={"button"}
            data-plasmic-override={overrides.button}
            className={classNames("__wab_instance", sty.button, {
              [sty.buttonborders_flatLeft]: hasVariant(
                $state,
                "borders",
                "flatLeft"
              ),
              [sty.buttonborders_flatRight]: hasVariant(
                $state,
                "borders",
                "flatRight"
              ),
              [sty.buttonprimary]: hasVariant($state, "primary", "primary")
            })}
            label={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___2JXft,
                  {
                    [sty.textborders_flatLeft___2JXftk3Sr5]: hasVariant(
                      $state,
                      "borders",
                      "flatLeft"
                    ),
                    [sty.textborders_flatRight___2JXftX97Nv]: hasVariant(
                      $state,
                      "borders",
                      "flatRight"
                    )
                  }
                )}
              >
                {hasVariant($state, "borders", "flatRight")
                  ? "Everything is yours"
                  : hasVariant($state, "borders", "flatLeft")
                  ? "Claim Free"
                  : "Go Become pro"}
              </div>
            }
            size={"extraLarge"}
            type={
              hasVariant($state, "borders", "flatLeft") ? "soft" : undefined
            }
          />
        </PlasmicLink__>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "h4", "link", "button"],
  freeBox: ["freeBox", "h4", "link", "button"],
  h4: ["h4"],
  link: ["link", "button"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  h4: "h4";
  link: "a";
  button: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPriceCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPriceCard__VariantsArgs;
    args?: PlasmicPriceCard__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPriceCard__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPriceCard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPriceCard__ArgProps,
          internalVariantPropNames: PlasmicPriceCard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPriceCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPriceCard";
  } else {
    func.displayName = `PlasmicPriceCard.${nodeName}`;
  }
  return func;
}

export const PlasmicPriceCard = Object.assign(
  // Top-level PlasmicPriceCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    h4: makeNodeComponent("h4"),
    link: makeNodeComponent("link"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicPriceCard
    internalVariantProps: PlasmicPriceCard__VariantProps,
    internalArgProps: PlasmicPriceCard__ArgProps
  }
);

export default PlasmicPriceCard;
/* prettier-ignore-end */
