/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pNbGo1JnjtEErG6Lk1GLW5

import * as React from "react";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: pNbGo1JnjtEErG6Lk1GLW5/projectModule
import { UserContext } from "../../../../context/UserContext"; // plasmic-import: RiWG8-LTAmNH/codeComponent

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  userContextProps?: Partial<
    Omit<React.ComponentProps<typeof UserContext>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, userContextProps } = props;

  return <UserContext {...userContextProps}>{children}</UserContext>;
}
