/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pNbGo1JnjtEErG6Lk1GLW5

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantscavMid9LmMHn } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: cavMID9LmMHn/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantscavMid9LmMHn
});
